### ISSUE TITLE
Create 'Create User' and 'Delete User' Functions

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#15]
### Goal: Create 'Create User' and 'Delete User' Functions to be used with Firebase

**Branch Name:** `create-delete-user`

### What You Have To Do

You should have gotten access to the firebase portal by now. If not, slack me and I'll get you all set ASAP!

Step 1: Install Firebase!

Using Firebase Admin **(with custom claims)**, create functions to do the following:
- Create a user. Parameters: `claim: number`
- Delete a user. Parameters: none

Each user should be given a claim on creation, and that claim will be determined by the `claim` param.

`claim` is of type **`number`**. The corresponding value and claim are as follows:
- 0: `mobile-entry` claim
- 1: `web-entry` claim
- 2: `evaluator` claim
- 3: `admin` claim

Create routes for these functions and test them out!

### Task Tracker:
- [x] Create branch
- [x] Create functions as specified
- [x] Create routes as specified
- [x] Test your function
- [x] Create a PR!
