### ISSUE TITLE
Create Initial Page Layout + NavBar

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#16]
### Goal: Create the Initial 3 Pages and a Navbar to Navigate Between Them

**Branch Name:** `init-page-layout`

### What You Have To Do

####Part 1:

Create a folder `pages` in `frontend/src`. In this folder, create the following three pages:
- `landing.tsx`
- `data-viz.tsx`
- `admin.tsx`

Put some kind of dummy text on each to distinguish them.

Then, using React Navigation, have `landing.tsx` display automatically from `App.tsx`.

####Part 2:

Create a folder `components` in `frontend/src`. Put your map component from last week into this folder, then create a new component in it called `navbar.tsx`. This navbar should be a simple 3 button navigation that allows the user to switch between the three pages you created earlier.

Put the navbar on each page and revel in your ability to switch between them!

### Task Tracker:
- [x] Create branch
- [x] Create pages as specified
- [x] Create component as specified
- [x] Test it all out
- [x] Create a PR!
