### ISSUE TITLE
Create 'Modify User' Function to be used with Firebase

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#18]
### Goal: Create 'Modify User' Function to be used with Firebase

**Branch Name:** `modify-user`

### What You Have To Do

You should have gotten access to the firebase portal by now. If not, slack me and I'll get you all set ASAP!

Step 1: Install Firebase!

Using Firebase Admin **(with custom claims)**, create function to change the claim of a user. Parameters: `new_claim: number`. When the claim of a user is changed, it should be done to that of param `new_claim`.

`new_claim` is of type **`number`**. The corresponding value and claim are as follows:
- 0: `mobile-entry` claim
- 1: `web-entry` claim
- 2: `evaluator` claim
- 3: `admin` claim

Create route for this function and test it out!

### Task Tracker:
- [x] Create branch
- [x] Create function as specified
- [x] Create route as specified
- [x] Test your function
- [x] Create a PR!
