### ISSUE TITLE
Create a Function To Query All Documents

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#2]
### Goal: Create a Function To Query All Documents In List of Clusters

**Branch Name:** `cluster-query-func`

### What You Have To Do
Read up on Mongo's query functions here: https://www.mongodb.com/developer/languages/javascript/node-crud-tutorial/
Create a function to query all documents. Function should return all **data** documents from nets from clusters in array `cluster-ids` that fall within the date range. Parameters should be:
- `cluster-ids` -  -  Type: `Array<number>`. The list of cluster IDs. Will not be left empty.
- `min-date` -  Type: `Date` or `number`. The earliest date that the query should return. If left empty, it should default to Jan. 1st, 2023.
- `max-date` -  -  Type: `Date` or `number`. The latest date the query should return. If left empty, it should default to the current date.
Create a route titled `get-cluster-data` that takes in the same parameters and test it out!

Note: This is the DB schema we're working with:
<img width="925" alt="image" src="https://github.com/cornellh4i/ctw-admin/assets/52248400/bf6bc767-3b9a-4736-af96-0e5625d0eadd">

### Task Tracker:
- [x] Create branch
- [x] Read documentation above
- [x] Create function as specified
- [x] Create route as specified
- [x] Test your function
- [x] Create a PR!
