### ISSUE TITLE
Create a Login Component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#20]
### Goal: Create a Login Component

**Branch Name:** `login-component`

### What You Have To Do

Using Firebase, create a login and recaptcha component, as per this guide: https://firebase.google.com/docs/auth/web/phone-auth?authuser=0&hl=en

You'll need access to the Firebase console, which you can find here: https://console.firebase.google.com/u/1/project/clean-the-world-50a0c/overview

...I do still need to add your netids though, and if I forget to ask during subteam, don't hesitate to slack me and I'll set you up!

It's a lot, but the tutorial is pretty thorough and should give you a solid understanding of what you're doing and why throughout the whole process.

Create a route, test it, and set up your PR!

### Task Tracker:
- [x] Create branch
- [x] Create function as specified
- [x] Create route as specified
- [x] Test your function
- [x] Create a PR!
