### ISSUE TITLE
Create A Function to Get a List of All Users 

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#21]
### Goal: Create A Function to Get a List of All Users 

**Branch Name:** `list-all-users`

### What You Have To Do

Create a backend function that returns a list of all users registered in Firebase. Firebase typically does this in batches (defaulting to a size of 1000) - Keep this batch size for now, but we might mess with it in the future.

Create a route, test it, and set up your PR!

### Task Tracker:
- [x] Create branch
- [x] Create function as specified
- [ ] Create route as specified
- [ ] Test your function
- [ ] Create a PR!
