### ISSUE TITLE
Create a Function To Obtain List of Clusters in Location Range

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#3]
### Goal: Create a Function To Obtain List of Clusters in Location Range

**Branch Name:** `location-query-func`

### What You Have To Do
Read up on Mongo's query functions here: https://www.mongodb.com/developer/languages/javascript/node-crud-tutorial/
Create a function to query all documents. Function should return a list of all cluster IDs that fall within the specified coordinates. It should take the following parameters:
- `lower-left` -  Type: `Array<number>`. Two numbers, representative of the coordinates for the lower left binding of the location range.
- `upper-right` -  Type: `Array<number>`. Two numbers, representative of the coordinates for the upper right binding of the location range.
Create a route titled `get_clusters_in_range` that takes in the same parameters and test it out!

Note: This is the DB schema we're working with:
<img width="925" alt="image" src="https://github.com/cornellh4i/ctw-admin/assets/52248400/bf6bc767-3b9a-4736-af96-0e5625d0eadd">

### Task Tracker:
- [x] Create branch
- [x] Read documentation above
- [x] Create function as specified
- [x] Create route as specified
- [x] Test your function
- [x] Create a PR!
