### ISSUE TITLE
Connect Graph to Data

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#37]
### Goal: Create an Early Data-Viz Implementation Using Your Component

**Branch Name:** `showcase-data-viz`

### What You Have To Do

Using the sample data-viz component you made previously:
- Create a volume / time graph as shown in the [hifis](https://www.figma.com/file/YdRF8K241Azh2ZMx99omJ8/H4I-CTW?type=design&node-id=1-328&mode=design&t=z4T51PMVUL4RsDaW-0)
- Use existing backend infrastructure to display data from backend! Feel free to input a bunch of dummy data to test with

### Task Tracker:
- [x] Create branch
- [x] Modify your component
- [x] Connect it to the backend
- [x] Test it out
- [ ] Create a PR!
