### ISSUE TITLE
Create a Function to Gather All Data Given a Net Model + Cluster ID

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#5]
### Goal: Create a Function to Gather All Data Given a Net Model + Cluster ID

**Branch Name:** `model-query-func`

### What You Have To Do
Create a function with the following parameters:
- `cluster-ids` - Type: `Array<number>`. The list of cluster IDs. Will not be left empty.
- `min-date` -  Type: `Date`. The earliest date that the query should return. If left empty, it should default to Jan. 1st, 2023.
- `max-date` -  Type: `Date`. The latest date the query should return. If left empty, it should default to the current date.
- `model` - Type: `Model`. This will be a custom type representing the model of fog net we are isolating. For now, just make a custom type with properties `name` (string) and `cost` (number).

Create a route that takes in the same parameters and test it out!

Note: This will use a lot of your code from last week. Try to consolidate and recycle where you can!

For reference, here's the new schema:
![Image](https://github.com/cornellh4i/ctw-admin/assets/52248400/8e3df576-9d0c-413a-9835-ade9b34b46e0)

### Task Tracker:
- [x] Create branch
- [x] Create function as specified
- [x] Create route as specified
- [x] Test your function
- [x] Create a PR!
