### ISSUE TITLE
Develop Simple Map Component

### ISSUE THREAD

**Issue by jfeuerstein** [cornellh4i/ctw-admin#7]
### Goal: Develop a Simple Map Component

**Branch Name:** `map-component`

### What You Have To Do
Look into React Simple Maps here: https://www.react-simple-maps.io/

Create a map component in the frontend with the following parameters:
- `bottom-left` - initial coordinates of the bottom left of the map's viewing window. Type: `Array<number>`
- `top-right` - initial coordinates of the top right of the map's viewing window. Type: `Array<number>`
- `clusters` - list of clusters to display. For now, assume that it is an Type: `Array<Array<number>>` (a list of coordinates, basically)

This component should:
- Show the map contained between `bottom-left` and `top-right`
- Display markers at each location in `clusters`. Markers should display some kind of filler text to be iterated on in the future
- Be responsive

### Task Tracker:
- [x] Create branch
- [x] Check out the docs above
- [x] Create that component!
- [x] Test it all out
- [x] Create a PR!
